POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "hjyemm1@icloud.com",
    "password": "password123"
}
###
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "firstName": "Harvey",
  "lastName": "Yemm",
  "email": "hjyemm1@icloud.com",
  "password": "password123",
  "gender": "male",
  "dateOfBirth": "1990-01-01",
  "phone": "+123456789"
}

###
GET http://localhost:4000/auth/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWE1MWEwZThhMGIzYzIyOThjY2NmNSIsImVtYWlsIjoiaGp5ZW1tQGljbG91ZC5jb20iLCJpYXQiOjE3Mjk3NzgwODUsImV4cCI6MTczMDM4Mjg4NX0.gpUZimcbGm8BvrU_GNjM8Pk-gmGl69wggsspmUmoKVM
###
DELETE  http://localhost:4000/auth/account/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTk2ZTM4M2VkYTdkNTk4ZjJmMGZjZiIsImVtYWlsIjoiaGp5ZW1tQGljbG91ZC5jb20iLCJpYXQiOjE3Mjk3MTk4NjQsImV4cCI6MTczMDMyNDY2NH0.sjuHvMatwc1rKRU2641vlQ5bHSpA3ObVndUUyFKZ7tw
###
